### PR TITLE
Change conversion of NTP64 and Timesamp to/from String

### LINKED ISSUE #15: Timestamp is not round-trip equivalent with Display and parse()
The `+ 1` at the end of the `impl From<Duration>` breaks stringifying and then parsing the same number back out.

https://github.com/atolab/uhlc-rs/blob/68bf15965061951bb4d11db9c54acf9ba5235b00/src/ntp64.rs#L231

The following test fails:
```rust
    #[test]
    fn test_exact_parse() {
        use std::str::FromStr;
        let id1: ID = ID::try_from([0x01]).unwrap();
        let ts1 = Timestamp::new(NTP64(100), id1);
        assert_eq!(ts1, Timestamp::from_str(&ts1.to_string()).unwrap());
    }
```

### PR DESCRIPTION
**Pull request by JEnoch**
As discussed in https://github.com/atolab/uhlc-rs/issues/15 in `0.7.0` and previous versions the formatting and conversion of `NTP64` and `Timestamp` into a String uses the RFC3339 representation, suffering of rounding and thus loss of precision when converting the fraction of seconds part into nanoseconds.  
The consequence was that conversion from/to String was not bijective (i.e. you might not get back the original value after a 2-ways conversion).

This PR changes the default conversion of `NTP64` and `Timestamp` into a String, formatting the time as an unsigned integer in decimal format. This conversion is lossless and bijective.

For conversion to RFC3339 format, those methods are added:
- `NTP64::to_string_rfc3339()`
- `NTP64::parse_rfc3339()`
- formatting with the alternate flag (e.g.: `println!("{:#}", my_ntp64);` )
- `Timestamp::to_string_rfc3339()`
- `Timestamp::parse_rfc3339()`
- formatting with the alternate flag (e.g.: `println!("{:#}", my_timestamp);` )

Note that those new methods are not available in `no_std` context.

Closes #15

### CODE REVIEW

File: src/ntp64.rs [hunk 1]
```diff
@@ -278,4 +322,36 @@ mod tests {
         );
         assert!(epoch_plus_counter_max.as_secs_f64() < 0.0000000035f64);
     }
+
+    #[test]
+    fn bijective_to_string() {
+        use crate::*;
+        use std::str::FromStr;
+        for n in 0u64..10000 {
+            let t = NTP64(n);
```
Comment (Mallets) [inline src/ntp64.rs:331]: I would randomly generate `n`.

File: src/ntp64.rs [hunk 2]
```diff
@@ -102,6 +115,29 @@ impl NTP64 {
     pub fn to_system_time(self) -> SystemTime {
         UNIX_EPOCH + self.to_duration()
     }
+
+    /// Convert to a RFC3339 time representation with nanoseconds precision.
+    /// e.g.: `"2024-07-01T13:51:12.129693000Z"``
+    #[cfg(feature = "std")]
+    pub fn to_string_rfc3339(&self) -> String {
```
Comment (Mallets) [inline src/ntp64.rs:122]: Should the function be called `to_string_rfc3339_lossy` To reflect the fact the conversion is lossy?

File: src/ntp64.rs [hunk 3]
```diff
@@ -209,17 +245,33 @@ impl SubAssign<u64> for NTP64 {
...
+    /// ```
     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
-        #[cfg(feature = "std")]
-        return write!(f, "{}", format_rfc3339_nanos(self.to_system_time()));
-        #[cfg(not(feature = "std"))]
-        return write!(f, "{:x}", self.0);
+        // if "{:#}" flag is specified, use RFC3339 representation
+        if f.alternate() {
+            #[cfg(feature = "std")]
+            return write!(f, "{}", format_rfc3339_nanos(self.to_system_time()));
```
Comment (Mallets) [inline src/ntp64.rs:263]:
```suggestion
           write!(f, "{}", format_rfc3339_nanos(self.to_system_time()));
```

File: src/ntp64.rs [hunk 4]
```diff
@@ -209,17 +245,33 @@ impl SubAssign<u64> for NTP64 {
...
+            #[cfg(not(feature = "std"))]
+            return write!(f, "{}", self.0);
```
Comment (Mallets) [inline src/ntp64.rs:265]:
```suggestion
            write!(f, "{}", self.0);
```

File: src/timestamp.rs [hunk 5]
```diff
@@ -48,11 +61,56 @@ impl Timestamp {
     pub fn get_diff_duration(&self, other: &Timestamp) -> Duration {
         (self.time - other.time).to_duration()
     }
+
+    /// Convert to a RFC3339 time representation with nanoseconds precision.
+    /// e.g.: `"2024-07-01T13:51:12.129693000Z/33"``
+    #[cfg(feature = "std")]
+    pub fn to_string_rfc3339(&self) -> String {
```
Comment (Mallets) [inline src/timestamp.rs:68]: Should the function be called `to_string_rfc3339_lossy` To reflect the fact the conversion is lossy?

File: src/ntp64.rs (hunk 3 above)
Comment (JEnoch) [reply src/ntp64.rs:263]: That's not possible because of the following `#[cfg...]`.
Removing the `return` and the `;` (required because a `fmt::Result` must be returned) the compiler returns this error:
```log
error: expected `;`, found `#`
   --> src/ntp64.rs:263:73
    |
262 |             #[cfg(feature = "std")]
    |             ----------------------- only `;` terminated statements or tail expressions are allowed after this attribute
263 |             write!(f, "{}", format_rfc3339_nanos(self.to_system_time()))
    |                                                                         ^ expected `;` here
264 |             #[cfg(not(feature = "std"))]
    |             - unexpected token
    ```

**Review by Mallets — APPROVED** [review]
